/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BloomButton {
        "callback_url": string;
        "consumer_email": string;
        "consumer_name": string;
        "items": Array<{
    amount: number;
    description: string;
    id: string;
  }>;
        "label": string;
        "merchant": string;
    }
}
declare global {
    interface HTMLBloomButtonElement extends Components.BloomButton, HTMLStencilElement {
    }
    var HTMLBloomButtonElement: {
        prototype: HTMLBloomButtonElement;
        new (): HTMLBloomButtonElement;
    };
    interface HTMLElementTagNameMap {
        "bloom-button": HTMLBloomButtonElement;
    }
}
declare namespace LocalJSX {
    interface BloomButton {
        "callback_url"?: string;
        "consumer_email"?: string;
        "consumer_name"?: string;
        "items"?: Array<{
    amount: number;
    description: string;
    id: string;
  }>;
        "label"?: string;
        "merchant"?: string;
        "onOncancel"?: (event: CustomEvent<{
    status: number;
  }>) => void;
        "onOnerror"?: (event: CustomEvent<{
    status: number;
  }>) => void;
        "onOnsuccess"?: (event: CustomEvent<{
    status: number;
    order: any;
    payment: string;
  }>) => void;
    }
    interface IntrinsicElements {
        "bloom-button": BloomButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bloom-button": LocalJSX.BloomButton & JSXBase.HTMLAttributes<HTMLBloomButtonElement>;
        }
    }
}
