/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BloomButton {
        "name": string;
    }
}
declare global {
    interface HTMLBloomButtonElement extends Components.BloomButton, HTMLStencilElement {
    }
    var HTMLBloomButtonElement: {
        prototype: HTMLBloomButtonElement;
        new (): HTMLBloomButtonElement;
    };
    interface HTMLElementTagNameMap {
        "bloom-button": HTMLBloomButtonElement;
    }
}
declare namespace LocalJSX {
    interface BloomButton {
        "name"?: string;
    }
    interface IntrinsicElements {
        "bloom-button": BloomButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bloom-button": LocalJSX.BloomButton & JSXBase.HTMLAttributes<HTMLBloomButtonElement>;
        }
    }
}
